import type {Metadata} from "next";
import {Inter} from "next/font/google";
import "./globals.css";
import React from "react";
import Header from "@/app/components/Header";
import Footer from "@/app/components/Footer";
import {headers} from "next/headers";

const inter = Inter({subsets: ["latin"]});

export const metadata: Metadata = {
    title: "Next WP Template",
    description: "Generated by create next app",
};

export default function RootLayout({children}: Readonly<{ children: React.ReactNode; }>) {

    return (
        <html lang="en">
            <body className={inter.className}>
                <Header/>
                    {children}
                <Footer/>
            </body>
        </html>
    );
}
